import { Options, Command } from "@effect/cli";
import { NodeContext, NodeRuntime } from "@effect/platform-node";
import { Effect } from "effect";
import { version } from "../package.json";
import { makeProject, TypedSnapshot } from "@typed-lang/compiler";
import { FileSystem } from "@effect/platform";
import { resolve, dirname } from "node:path";

// Define the top-level command
const command = Command.make(
  "compile",
  {
    dir: Options.directory("dir").pipe(Options.withDefault(process.cwd())),
    mode: Options.choice("mode", ["single", "multiple"]).pipe(
      Options.withDefault("multiple")
    ),
    output: Options.choice("output", ["js", "ts", "both"]).pipe(
      Options.withDefault("both")
    ),
    outDir: Options.text("outDir").pipe(Options.withDefault("dist")),
    tsConfig: Options.text("tsConfig").pipe(Options.withDefault("tsconfig.json")),
  },
  (args) =>
    Effect.gen(function* () {
      const srcDir = resolve(process.cwd(), args.dir);
      const outDir = resolve(process.cwd(), args.outDir);
      const fs = yield* FileSystem.FileSystem;
      const files = yield* (args.output === "js" ? findAllFilesInDirectory(srcDir) : findAllTypedFilesInDirectory(srcDir));

      if (yield* fs.exists(outDir)) {
        yield* fs.remove(outDir, { recursive: true });
      }

      yield* fs.makeDirectory(outDir, { recursive: true });

      const project = makeProject({
        directory: srcDir,
        tsConfigFileName: args.tsConfig,
        outputMode: args.mode,
        outDir,
      })

      const compiler = project.compiler

      for (const file of files) {
        project.addFile(file)
      }


      if (args.output === "ts" || args.output === "both") {
        // Write all the files generated by the compiler
        for (const fileName of compiler.getScriptFileNames()) {
          const snapshot = compiler.getSnapshot(fileName)!;
          yield* writeSnapshot(snapshot, args);
        }
      }

      if (args.output === "js" || args.output === "both") {
        const outputFiles = project.emit()

        for (const file of outputFiles) {
          const outFileName = getOutFileName(srcDir, outDir, file.name);
          yield* fs.writeFileString(outFileName, file.text);
        }
      }
    })
);

// Set up the CLI application
const cli = Command.run(command, {
  name: "Typed Language CLI",
  version,
});

// Prepare and run the CLI application
cli(process.argv).pipe(Effect.provide(NodeContext.layer), NodeRuntime.runMain);

function findAllFilesInDirectory(dir: string) {
  return Effect.gen(function* () {
    const fs = yield* FileSystem.FileSystem;
    const files = yield* fs.readDirectory(dir, { recursive: true });
    return files.map((p) => resolve(dir, p));
  });
}

function findAllTypedFilesInDirectory(dir: string) {
  return Effect.gen(function* () {
    const files = yield* findAllFilesInDirectory(dir);
    return files.filter((f) => f.endsWith(".typed"));
  });
}

function getOutFileName(dir: string, outDir: string, fileName: string) {
  return fileName.replace(dir, outDir);
}

function writeSnapshot(
  snapshot: TypedSnapshot,
  args: { dir: string; outDir: string }
) {
  return Effect.gen(function* () {
    const fs = yield* FileSystem.FileSystem;
    const outFileName = getOutFileName(
      resolve(process.cwd(), args.dir),
      resolve(process.cwd(), args.outDir),
      snapshot.fileName
    );

    yield* fs.makeDirectory(dirname(outFileName), { recursive: true });

    yield* fs.writeFileString(outFileName, snapshot.getText(), {});
    yield* fs.writeFileString(
      outFileName + ".map",
      JSON.stringify(snapshot.map)
    );
  });
}
